[theme]
base                     = "dark"
primaryColor             = "#27ae60"
backgroundColor          = "#0d1117"
secondaryBackgroundColor = "#161b27"
textColor                = "#e2e8f0"
font                     = "sans serif"
